##Self Dockerimage on latest build##
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash-file.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logs:/var/log
    ports:
      - "5000:5000"
    links:
      - elasticsearch
      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch    

volumes:
  esdata1:
    driver: local  
