apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
      app: config-app
      tier: backend      
  ports:
    - port: 8888
      protocol: TCP
      nodePort: 32444
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: config-deployment
spec:
  selector:
    matchLabels:
      app: config-app
      tier: backend
      track: stable
  replicas: 4 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: config-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: config
        image: gcr.io/wms-as-a-service/configservice
        envFrom:
        - configMapRef:
            name: wms-env-config        
        env:
        - name: KAFKA_HOST
          value: "10.128.0.2"
        - name: GIT_URL
          value: https://github.com/knpillutla/appconfig                    
        
        ports:
        - name: http
          containerPort: 8888
