apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
      app: config-app
      tier: backend      
  ports:
    - port: 8888
      protocol: TCP
      nodePort: 32444
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: config-deployment
spec:
  selector:
    matchLabels:
      app: config-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: config-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: config
        image: gcr.io/wms-as-a-service/configservice
        env:
        - name: KAFKA_HOST
          value: "10.128.0.2"
        - name: DB_URL
          value: "jdbc:postgresql://35.199.61.35/postgres"
        - name: GIT_URL
          value: "https://github.com/knpillutla/appconfig"                    
        - name: SERVER_PORT
          value: "8888"                  
        
        ports:
        - name: http
          containerPort: 8888
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)
        ports:
        - containerPort: 5000
