apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: config-deployment
spec:
  selector:
    matchLabels:
      app: wms
      tier: backend
      track: stable
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wms
        tier: backend
        track: stable
    spec:
      containers:
      - name: config
        image: gcr.io/wms-as-a-service/configservice
        envFrom:
        - configMapRef:
            name: wms-env-config        
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: KAFKA_HOST
          value: "10.128.0.2"
        - name: POSTGRES_HOST
          value: "35.199.61.35"          
        - name: LOG_DIR
          value: "/var/logs"                    
        
        ports:
        - name: http
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
      app: wms
      tier: backend      
  ports:
    - port: 8888
      protocol: TCP
      nodePort: 32444
  type: NodePort
