apiVersion: v1
kind: Service
metadata:
  name: customer-order
spec:
  selector:
      app: customer-order-app
      tier: backend
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: customer-order-deployment
spec:
  selector:
    matchLabels:
      app: customer-order-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: customer-order-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: customer-order
        image: gcr.io/wms-as-a-service/customer-order
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prodgcp"
        - name: CONFIG_SERVICE
          value: http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)
        - name: KAFKA_HOST
          value: $(KAFKA_CLUSTER_SERVICE_HOST):$(KAFKA_CLUSTER_SERVICE_PORT)
        - name: POSTGRES_HOST
          value: $(CUSTOMERORDER_DB_SERVICE_HOST):$(CUSTOMERORDER_DB_SERVICE_PORT)
        - name: POSTGRES_DB
          value: "customerorder"                  
        - name: POSTGRES_USER
          value: "customerorder"                  
        - name: POSTGRES_PWD
          value: "customerorder"                  
        - name: SERVER_PORT
          value: "8080"                  
        ports:
        - containerPort: 8080
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)
        ports:
        - containerPort: 5000
