apiVersion: v1
kind: Deployment
metadata:
  name: wms-app
  namespace: wms-namespace
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wms-app
  template:
    metadata:
      labels:
        app: wms-app
    spec:
      containers:
      - name: config
        image: gcr.io/wms-as-a-service/configservice
        envFrom:
        - configMapRef:
            name: wms-gcp-env        
        resources: 
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 125Mi
        ports:
        - name: http
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 0
          timeoutSeconds: 1
      - name: picking
        image: gcr.io/wms-as-a-service/picking
        envFrom:
        - configMapRef:
            name: wms-gcp-env        
        resources: 
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 125Mi
        ports:
        - name: http
          containerPort: 5001
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5001
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5001
          initialDelaySeconds: 0
          timeoutSeconds: 1
