##Self Dockerimage on latest build##
version: '3.3'
services:
  nginx-lb:
    image: nginx
    restart: always
    ports:
      - 80:80
    environment:
      - JAVA_OPTS=-Xmx128m
  mypostgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - JAVA_OPTS=-Xmx512m
      - POSTGRES_PASSWORD=postgres
  zookeeper:
    depends_on:
      - mypostgres  
    image: confluentinc/cp-zookeeper:5.0.0
    restart: always
    ports:
      - 32181:32181
    environment:
      - JAVA_OPTS=-Xmx512m
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000

      
  kafka:
    depends_on:
      - zookeeper  
    image: confluentinc/cp-kafka:5.0.0
    restart: always
    ports:
      - 29092:29092
    environment:
      - JAVA_OPTS=-Xmx512m
      - KAFKA_ZOOKEEPER_CONNECT=192.168.56.1:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.56.1:29092
  picking:
    depends_on:
      - kafka  
    image: wmspicking:latest
    ports:
      - 9093:9093
      - 8000:8000
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev

