apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
      app: inventory-app
      tier: backend
  ports:
    - port: 80
      nodePort: 32446
      targetPort: 80
  type: NodePort
#  loadBalancerIP: 35.221.40.3
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: inventory-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: inventory
        image: gcr.io/formal-theater-221701/inventory
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: "http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)"
        - name: SERVER_PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 200
          periodSeconds: 20
        ports:
        - containerPort: 80
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        ports:
        - containerPort: 5000
