apiVersion: v1
kind: Service
metadata:
  name: orderplanner
spec:
  selector:
      app: orderplanner-app
      tier: backend
  ports:
    - port: 443
      nodePort: 32447
      targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: orderplanner-deployment
spec:
  selector:
    matchLabels:
      app: orderplanner-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: orderplanner-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: orderplanner
        image: gcr.io/bright-seer-219503/orderplanner
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: "http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)"
        - name: SERVER_PORT
          value: "443"
        ports:
        - containerPort: 443
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        ports:
        - containerPort: 5000
