apiVersion: v1
kind: Service
metadata:
  name: picking
spec:
  selector:
      app: picking-app
      tier: backend
  ports:
    - port: 80
      nodePort: 32449
      targetPort: 80
  type: NodePort
#  loadBalancerIP: 35.221.19.118
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: picking-deployment
spec:
  selector:
    matchLabels:
      app: picking-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 500
  template:
    metadata:
      labels:
        app: picking-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: picking
        image: gcr.io/formal-theater-221701/picking
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: "http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)"
        - name: SERVER_PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /picking/v1/health
            port: 80
          initialDelaySeconds: 500
          timeoutSeconds: 2
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /picking/v1/ready
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 30
        ports:
        - containerPort: 80
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        ports:
        - containerPort: 5000
