apiVersion: v1
kind: Service
metadata:
  name: picking
spec:
  selector:
      app: picking-app
      tier: backend
  ports:
    - port: 8080
      nodePort: 32449
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: picking-deployment
spec:
  selector:
    matchLabels:
      app: picking-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: picking-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: picking
        image: gcr.io/bright-seer-219503/picking
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: "http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)"
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        ports:
        - containerPort: 5000
