apiVersion: v1
kind: Service
metadata:
  name: myredis
spec:
  selector:
      app: myredis-app
      tier: backend
  ports:
    - port: 6379
      nodePort: 32552
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myredis-deployment
spec:
  selector:
    matchLabels:
      app: myredis-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myredis-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: myredis
        image: redis
        env:
        - name: SERVER_PORT
          value: "6379"
        ports:
        - containerPort: 6379
