apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
      app: shipping-app
      tier: backend
  ports:
    - port: 80
      nodePort: 32450
      targetPort: 80
  type: NodePort
#  loadBalancerIP: 35.227.19.34
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: shipping-deployment
spec:
  selector:
    matchLabels:
      app: shipping-app
      tier: backend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 500
  template:
    metadata:
      labels:
        app: shipping-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: shipping
        image: gcr.io/lustrous-bounty-224202/shipping
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: "http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)"
        - name: SERVER_PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /shipping/v1/health
            port: 80
          initialDelaySeconds: 600
          timeoutSeconds: 2
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /shipping/v1/ready
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 30
        ports:
        - containerPort: 80
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        ports:
        - containerPort: 5000
