apiVersion: v1
kind: Service
metadata:
  name: wmsui
spec:
  selector:
      app: wmsui-app
      tier: frontend
  ports:
    - port: 80
      nodePort: 32455
      targetPort: 80
  type: LoadBalancer
#  loadBalancerIP: 35.227.19.34
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wmsui-deployment
spec:
  selector:
    matchLabels:
      app: wmsui-app
      tier: frontend
      track: stable
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wmsui-app
        tier: frontend
        track: stable
    spec:
      containers:
      - name: wmsui
        image: gcr.io/formal-theater-221701/wmsui
        env:
        - name: USER_AUTH_SERVICE
          value: "http://$(USER_SERVICE_HOST):$(USER_SERVICE_PORT)"
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        - name: CONFIG_SERVICE
          value: "http://$(CONFIG_SERVICE_HOST):$(CONFIG_SERVICE_PORT)"
        - name: SERVER_PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 500
          periodSeconds: 30
        ports:
        - containerPort: 80
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.3.2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "gcp"
        ports:
        - containerPort: 5000
