##Self Dockerimage on latest build##
version: '3.0'
services:
  config-server:
    image: wms/configservice
    container_name: config-server
    ports:
      - 8888:8888
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=gcp
      - KAFKA_HOST=35.221.18.46
    logging:
        driver: json-file

  picking:
    depends_on:
      - config-server
    image: wms/picking
    container_name: picking
    ports:
      - 9093:9093
      - 8000:8000
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=gcp
      - KAFKA_HOST=35.221.18.46
      - POSTGRES_HOST=35.199.61.35
      - LOG_DIR=./logs

volumes:
  esdata1:
    driver: local  