kubectl apply -f postgres-configdb-service.yaml
kubectl apply -f postgres-customerorderdb-service.yaml
kubectl apply -f postgres-orderplannerdb-service.yaml
kubectl apply -f postgres-shipmentdb-service.yaml
kubectl apply -f postgres-inventorydb-service.yaml
kubectl apply -f postgres-pickdb-service.yaml
kubectl apply -f postgres-packdb-service.yaml
kubectl apply -f postgres-printdb-service.yaml
kubectl apply -f postgres-shipenginedb-service.yaml
kubectl apply -f postgres-workflowdb-service.yaml
kubectl apply -f postgres-wmse2edb-service.yaml
