---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    name: kafka
spec:
  ports:
  - name: kafka1port
    protocol: "TCP"
    port: 31111
    targetPort: 9092
  selector:
    app: kafka-app
    id: "0"
  type: LoadBalancer
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kafka-app
  name: kafka-deployment
spec:
  template:
    metadata:
      labels:
        app: kafka-app
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "35.245.101.144"
        - name: KAFKA_ADVERTISED_PORT
          value: "$(KAFKA_CLUSTER_SERVICE_PORT_KAFKA1PORT)"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "$(ZOOKEEPER_1_SERVICE_HOST):$(ZOOKEEPER_1_SERVICE_PORT)"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: "admintome-test:1:1"
        ports:
        - containerPort: 9092
