apiVersion: v1
kind: Service
metadata:
  name: customerorder-db
spec:
  selector:
      app: customerorder-db-app
      tier: backend
  ports:
  - name: customerorder-db
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  type: LoadBalancer
#  loadBalancerIP: 35.221.40.3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customerorder-db-deployment
spec:
  selector:
    matchLabels:
      app: customerorder-db-app
      tier: backend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: customerorder-db-app
        tier: backend
    spec:
      containers:
      - image: postgres:11.1
        name: postgres
        env:
        - name: "POSTGRES_DB"
          value: "customerorder"
        - name: "POSTGRES_PASSWORD"
          value: "customerorder"
        - name: "POSTGRES_USER"
          value: "customerorder"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi