apiVersion: v1
kind: Service
metadata:
  name: shipengine-db
spec:
  selector:
      app: shipengine-db-app
      tier: backend
  ports:
  - name: shipengine-db
    protocol: "TCP"
    port: 5433
    targetPort: 5432
  type: NodePort
#  loadBalancerIP: 35.221.40.3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipengine-db-deployment
spec:
  selector:
    matchLabels:
      app: shipengine-db-app
      tier: backend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: shipengine-db-app
        tier: backend
    spec:
      containers:
      - image: postgres:11.1
        name: postgres
        envFrom:
        - configMapRef:
            name: wms-config
        env:
        - name: "POSTGRES_DB"
          value: "$(SHIPENGINE_DB_DB)"
        - name: "POSTGRES_PASSWORD"
          value: "$(SHIPENGINE_DB_PWD)"
        - name: "POSTGRES_USER"
          value: "$(SHIPENGINE_DB_USER)"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: shipenginedbvolmount
          mountPath: /var/lib/shipenginedb/data
          subPath: shipenginedbvolmount
      volumes:
        - name: shipenginedbvolmount
          persistentVolumeClaim:
            claimName: shipenginedb-vol-claim
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shipenginedb-vol-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi