apiVersion: v1
kind: ConfigMap
metadata:
  name: wms-config
data:
  SPRING_PROFILES_ACTIVE: "prodgcp,swagger,zipkin"
  SECURITY_OAUTH2_CLIENT_CLIENT_ID: "internal"
  SECURITY_OAUTH2_CLIENT_CLIENT_SECRET: "internal"
  SECURITY_OAUTH2_RESOURCE_USER_INFO_URI: "http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo"
  JHIPSTER_SLEEP: "10"
  SERVER_PORT: "80"
  CONFIG_DB_DB: "config"
  CONFIG_DB_USER: "config"
  CONFIG_DB_PWD: "config"  
  CUSTOMERORDER_DB_DB: "customerorder"
  CUSTOMERORDER_DB_USER: "customerorder"
  CUSTOMERORDER_DB_PWD: "customerorder"
  ORDERPLANNER_DB_DB: "orderplanner"
  ORDERPLANNER_DB_USER: "orderplanner"
  ORDERPLANNERDB_PWD: "orderplanner"  
  INVENTORY_DB_DB: "inventory"
  INVENTORY_DB_USER: "inventory"
  INVENTORY_DB_PWD: "inventory"
  SHIPMENT_DB_DB: "shipment"
  SHIPMENT_DB_USER: "shipment"
  SHIPMENT_DB_PWD: "shipment"
  PICK_DB_DB: "pick"
  PICK_DB_USER: "pick"
  PICK_DB_PWD: "pick"
  PACK_DB_DB: "pack"
  PACK_DB_USER: "pack"
  PACK_DB_PWD: "pack"
  PRINT_DB_DB: "print"
  PRINT_DB_USER: "print"
  PRINT_DB_PWD: "print"
  SHIPENGINE_DB_DB: "shipengine"
  SHIPENGINE_DB_USER: "shipengine"
  SHIPENGINE_DB_PWD: "shipengine"
  WORKFLOW_DB_DB: "workflow"
  WORKFLOW_DB_USER: "workflow"
  WORKFLOW_DB_PWD: "workflow"
  WMSE2E_DB_DB: "wmstest"
  WMSE2E_DB_USER: "wmstest"
  WMSE2E_DB_PWD: "wmstest"
  