apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose-dev-elk.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - args:
        - logstash
        - -f
        - /etc/logstash/conf.d/logstash-file.conf
        image: docker.elastic.co/logstash/logstash:6.3.2
        name: logstash
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
