##Self Dockerimage on latest build##
version: '3.0'
services:
   picking:
    image: wms/picking
    container_name: picking
    ports:
      - 9093:9093
      - 8000:8000
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9093
      - CONFIG_SERVICE=http://localhost:8888
 
