##Self Dockerimage on latest build##
version: '3.0'
services:
  picking:
    depends_on:
      - mypostgres
      - kafka
    image: wmspicking:latest
    ports:
      - 9093:9093
      - 8000:8000
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev

