##Self Dockerimage on latest build##
version: '3.0'
services:
  config-server:
    image: wms/configservice
    container_name: config-server
    ports:
      - 8888:8888
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
    logging:
        driver: json-file

  picking:
    depends_on:
      - config-server
    image: wms/picking
    container_name: picking
    ports:
      - 9093:9093
      - 8000:8000
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9093
       - KAFKA_HOST=192.168.56.1:29092

