##Self Dockerimage on latest build##
version: '3.0'
services:
   customer-order:
    image: wms/customer-order
    container_name: customer-order
    ports:
      - 9010:9010
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9010
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
   orderplanner:
    image: wms/orderplanner
    depends_on:
      - customer-order
    container_name: orderplanner
    ports:
      - 9011:9011
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9011
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
   inventory:
    image: wms/inventory
    depends_on:
      - orderplanner
    container_name: inventory
    ports:
      - 9012:9012
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9012
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
   picking:
    image: wms/picking
    depends_on:
      - inventory
    container_name: picking
    ports:
      - 9013:9013
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9013
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
   packing:
    image: wms/packing
    depends_on:
      - picking
    container_name: packing
    ports:
      - 9014:9014
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9014
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
   shipping:
    image: wms/shipping
    depends_on:
      - orderplanner
    container_name: shipping
    ports:
      - 9015:9015
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9015
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
 
   eventMonitor:
    image: wms/event-monitor
    depends_on:
      - orderplanner
    container_name: eventMonitor
    ports:
      - 9016:9016
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9016
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
      - REDIS_HOST=192.168.56.1
      - REDIS_PORT=6379
   user:
    image: wms/user
    depends_on:
      - orderplanner
    container_name: user
    ports:
      - 9017:9017
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9017
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
