##Self Dockerimage on latest build##
version: '3.0'
services:
   picking:
    image: wms/picking
    container_name: picking
    ports:
      - 9093:9093
      - 8000:8000
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=9093
      - CONFIG_SERVICE=http://192.168.56.1:8888
      - POSTGRES_HOST=192.168.56.1:5432
      - KAFKA_HOST=192.168.56.1:29092
 
